### ISSUE TITLE
Proposal: Remove Flash dependency in VMDIRAC charts

### ISSUE THREAD

**Issue by myco** [DIRACGrid/VMDIRAC#105]
It is not easy with Flash and some Linux systems. What about to change Flash charts to some javascript based charts like Highcharts or other ?
https://github.com/highcharts/highcharts
/Rafal

**Comment by zmathe** [comment]
there are no Flash charts in VMDIRAC as fas as I remember. Could you please point me the code were you saw it? In addition, we must not introduce new dependencies, if it is not needed. We have nice graphical library in Sencha (https://docs.sencha.com/extjs/6.0.2/guides/components/introduction_to_charting.html)

**Comment by myco** [comment]
There are Flash charts in VMDIRAC!
VMDIRAC is using  google.visualization 1.0 charts which are based on Flash.
So that I constantly get message about broken Flash player when I try to use VMDIRAC monitoring.

For me, main feature of charts library should be interactive zoom in/out time based chart, like this one
https://www.highcharts.com/demo/line-time-series
I think that ExtJS charts not offering this, also actual Flash solution is bad, so that I proposed Highcharts. Any alternatives?

**Comment by atsareg** [comment]
YEs, we certainly have charts done with Google tools that we have to get rid off. What should be the replacement is a point to discuss. We can use charts from Sencha, but for accounting like plots we can use the good old DIRAC Plotting service.

**Comment by zmathe** [comment]
ok, I was not aware that VMDIRAC has some plots. After checking the code, I see we are having the same plotting system as we had in WebAppDIRAC.
We decided a long time ago that we use the Sencha graphical library, which almost fulfils what we need. Most of the plots are already based on Sencha in WebAppDIRAC. I am not favour using an external graphical library at all. It was a very bad decision for using google tools. I do not want to repeat the same mistake again.... We know sencha will work for everyone event outside EU :) and we have full control.

**Comment by zmathe** [comment]
I do not think you want more complex one: http://examples.sencha.com/extjs/6.0.2/examples/modern/stockapp/index.html

**Comment by myco** [comment]
ExtJS charts should be sufficient

**Comment by sfayer** [comment]
I don't think this was ever switched, but Google Charts itself now seems to be Javascript based. In my tests (on a Linux PC without flash) all of the charts appears to be working properly now, so I'm going to close this issue. Please open a new issue with specific details if you're still having problems.
