### ISSUE TITLE
Openshift machine-api

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/VMDIRAC#127]
Discussing with some people, I had the impression that openshift machine-api is doing just what VMDIRAC tries to do: spawn machines on various cloud providers. Maybe it is worth investigating https://github.com/openshift/machine-api-operator

**Comment by sfayer** [comment]
Hi Chris,

I've had a look at this and I don't think it's something that we can readily do...  It isn't clear how much of OpenShift we'd actually need to install/configure to make the machine-api work and even then it doesn't appear to support the variety of back-end platforms/providers that we already use (it seems to have more of a focus on commercial clouds as you might expect).

If we wanted to make the backends more standard, then using a lower-level library like libcloud to abstract away the different cloud interfaces may be the way to go. I suspect even that is only worth doing if our current backends stop working or if we need to support something new.

Regards,
Simon
