### ISSUE TITLE
Migrate all the specific cloud details to libcloud

### ISSUE THREAD

**Issue by acasajus** [DIRACGrid/VMDIRAC#14]
Use [libcloud](http://libcloud.apache.org/) to talk to the different providers

**Comment by acasajus** [comment]
CC to @vfalbor to keep track of this issue.

**Comment by vmendez** [comment]
libcloud opennebula is based on OCCI 0.8 for different ONE servers up to 3.2, wich we already have implemented
libcloud openstack is based in nova api, I will try it when I get some nova endpoint access

**Comment by vmendez** [comment]
libcloud has been used to nova-1.1 and tested, 
the floating-ip methods are not included on libcloud and has been done with python nova client

**Comment by vmendez** [comment]
issue to be closed when integration done
