### ISSUE TITLE
VM instantiation: multiple options

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/VMDIRAC#16]
As agreed with point 1.1 of http://indico.cern.ch/getFile.py/access?sessionId=6&resId=0&materialId=1&confId=238601: 

1.1) VM Instantiation:
It has to be possible to select between 2 different instantiation scheduling algorithm: Jobs-driven and Slots-driven. There should be the possibility to switch from one to the other based on the targeted cloud.
- Jobs-driven: VMDIRAC will instantiate VM only when there are jobs in the task queues.
- Slots-driven: VMDIRAC will instantiate VM independently from if there are jobs in the task queues. All the cloud "slots" will be taken

This will require that we know exactly how many "slots" are available. This is something to be added to the Cloud drivers (bear in mind https://github.com/DIRACGrid/VMDIRAC/issues/15)

**Comment by vmendez** [comment]
1) jobs-driven is currently implemented 
2) slots-driven is in progress, we are implementing a per end-point max number of VMs together with an end-point policy of "static" -> slots driven or "elastic" -> jobs driven

**Comment by vmendez** [comment]
It has been developed and succesfully tested at PIC cloud (same implementation for all cloud managers)
To be integrated  at:
[v0r7]
NEW: endpoint vmPolicy "static" -> slots driven, indicated by maxEndpointInstances, endpoint CS parameter
     endpoint vmPolicy "elastic" -> jobs driven, one by one
