### ISSUE TITLE
Use of Cloud "Sites"

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/VMDIRAC#18]
As agreed with point 2 of http://indico.cern.ch/getFile.py/access?sessionId=6&resId=0&materialId=1&confId=238601:

Every cloud resource should be defined in a way to be fully compatible with the existing DIRAC tools (e.g. WMS, TS, RSS). The CS /Resources section has to be used. We identified a direct parallelism between the "usual" sites definition, and the cloud one. The example is in the doc.

This task is just to make sure that this requirement is not forgotten, and that tests will be done to be sure we don't find surprises. It also means that RSS might need some adaptation.

**Comment by ubeda** [comment]
On my hands now.

**Comment by ubeda** [comment]
Postponed until dirac v7r0 is out. Otherwise, we will have to re-do it again.

**Comment by atsareg** [comment]
Done in VMDIRAC v2
