### ISSUE TITLE
VMDIRAC Images CS Config

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/VMDIRAC#28]
I propose to reshuffle  a little bit the CS to make code and config simpler.
Now we have

```
Images
  Image1
    bootImageName
    contextMethod
    random strings
  Image2
    bootImageName
    contextMethod
    random strings
```

I propose to order it as follows

```
Images
  Image1
    bootImageName
    contextMethod = ssh
    ssh
      random strings
  Image2
    bootImageName
    contextMethod = adhoc
    adhoc
      random strings
```

What do you think @vmendez ?
I can prepare quickly a helper to make this kind of things completely transparent.

( a similar idea would apply for the endpoints )

**Comment by vmendez** [comment]
It's seems reasoable.
A detail to clarify would be if the "random strings" can be divided in two
parts, those strings independents of the contextMethod and others
underneath the contextMethod, and if this eventual clasiffication has any
functional advantage.
This is a question.

Víctor

2013/3/26 ubeda notifications@github.com

> I propose to reshuffle a little bit the CS to make code and config simpler.
> Now we have
> 
> Images
>   Image1
>     bootImageName
>     contextMethod
>     random strings
>   Image2
>     bootImageName
>     contextMethod
>     random strings
> 
> I propose to order it as follows
> 
> Images
>   Image1
>     bootImageName
>     contextMethod = ssh
>     ssh
>       random strings
>   Image2
>     bootImageName
>     contextMethod = adhoc
>     adhoc
>       random strings
> 
> What do you think @vmendez https://github.com/vmendez ?
> I can prepare quickly a helper to make this kind of things completely
> transparent.
> 
> ( a similar idea would apply for the endpoints )
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/issues/28
> .

## 

Víctor Méndez Muñoz
LHCb Tier1 Contact
Port d'Informació Científica (PIC)
Tel: +34935813772   Web: http://www.pic.es

PIC is maintained through a collaboration agreement between CIEMAT
(Ministerio de Ciencia e Innovación),
ECO (Generalitat de Catalunya), Universitat Autònoma de Barcelona and IFAE

---

IFAE provides the e-mail service used by PIC and requires this notice:
Avis - Aviso - Legal Notice:  http://www.ifae.es/legal.html

**Comment by ubeda** [comment]
This is more or less on place. I think this issue can be closed.
