### ISSUE TITLE
Nova11 terminate instance

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/VMDIRAC#29]
ping @vmendez 

I'm refactoring Nova11 and NovaImage modules, and I have the following question:

Why Nova11 does not make use of libcloud.compute.openstack.OpenStackNodeDriver.ex_delete_image to terminate images ?

**Comment by vmendez** [comment]
Hi Mario,

We have agree to use libcloud when possible, but I was using pynovaclient
without any particular reason,
You are right to change this to libcloud

Thanks
Víctor

2013/4/2 ubeda notifications@github.com

> ping @vmendez https://github.com/vmendez
> 
> I'm refactoring Nova11 and NovaImage modules, and I have the following
> question:
> 
> Why Nova11 does not make use of
> libcloud.compute.openstack.OpenStackNodeDriver.ex_delete_image to terminate
> images ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/issues/29
> .

## 

Víctor Méndez Muñoz
LHCb Tier1 Contact
Port d'Informació Científica (PIC)
Tel: +34935813772   Web: http://www.pic.es

PIC is maintained through a collaboration agreement between CIEMAT
(Ministerio de Ciencia e Innovación),
ECO (Generalitat de Catalunya), Universitat Autònoma de Barcelona and IFAE

---

IFAE provides the e-mail service used by PIC and requires this notice:
Avis - Aviso - Legal Notice:  http://www.ifae.es/legal.html

**Comment by ubeda** [comment]
Ok, I will proceed then.
