### ISSUE TITLE
Security properties for VMDIRAC

### ISSUE THREAD

**Issue by vmendez** [DIRACGrid/VMDIRAC#35]
Properties for VirtualMachineManagerHandler
a) "VirtualMachine" those used by VirtualMachineMonitor from the VM
b) "VirtualMachineManager" those used by groups to allow different operations (dirac_admin -> stop, user -> view, anonymous ? )

Define the new properties in:
Core/Security/Properties.py

**Comment by acasajus** [comment]
VirtualMachine is ok

For VirtualMachineManager you can user ServiceAdministrator that is already defined. What do you think?

**Comment by ubeda** [comment]
What about making use of SiteManager for VirtualMachineManager ?

**Comment by acasajus** [comment]
I don't know if the privileges are the same. Site managers do not have to
be also VM managers. Keep in mind that a VMManager will be essentially like
JobAdmin but for VMs

**Comment by ubeda** [comment]
Agree.

**Comment by ubeda** [comment]
Guys, I'm facing this issue now installing VMDIRAC on LHCb development setup. I need a conclusion.

**Comment by vmendez** [comment]
Today I am really bussy, but tomorrow frid 17th, I am going to UB to talk
with Adri about this and other issues.

2013/5/15 ubeda notifications@github.com

> Guys, I'm facing this issue now installing VMDIRAC on LHCb development
> setup. I need a conclusion.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/issues/35#issuecomment-17944762
> .

## 

Víctor Méndez Muñoz
LHCb Tier1 Contact
Port d'Informació Científica (PIC)
Tel: +34935813772   Web: http://www.pic.es

PIC is maintained through a collaboration agreement between CIEMAT
(Ministerio de Ciencia e Innovación),
ECO (Generalitat de Catalunya), Universitat Autònoma de Barcelona and IFAE

---

IFAE provides the e-mail service used by PIC and requires this notice:
Avis - Aviso - Legal Notice:  http://www.ifae.es/legal.html

**Comment by vmendez** [comment]
After chat with Adri and Ricardo we conclude to force the propoerties in the source, in this manner no errors can be done on a particular setup, if the properties are not the correct, the VMDIRAC will not work.
I am going to implement something like:

```
credDict = self.getRemoteCredentials()
if not Properties.VM_BLABLA in credDict[ 'properties' ]:
```

Two properties:
VM_MONITOR  for the services of the VM Manager Handler which are RPC from VM Monitor Agent
VM_MANAGER for the web and command interface operations (bassically stop command) this porperty can be asigned to whatever user or group in charge of the VM management

**Comment by ubeda** [comment]
Ok, sounds good to me. 

Just a comment, for the service, it should be enough having a proper CS setup to handle the properties.

Thanks !

Pinging Federico to keep him in the loop @fstagni

**Comment by vmendez** [comment]
For convergence with EGI VM policy (https://documents.egi.eu/public/RetrieveFile?docid=771&version=4&filename=EGI-SPG-VMEndorsementOperation-771-V3.pdf) we chanage the name VM_MANANGER to VM_OPERATOR
I would say that the best way to fit these requirements is to avoid service or robot proxies but using VM_OPERATOR proxy
