### ISSUE TITLE
Refresh pilot version inside VMs

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/VMDIRAC#36]
VMMonitorAgent must look after the PilotVersion being in sync between the CS and the local dirac.cfg. 

In order to do so, I has to overwrite dirac.cfg and touch a file named "stop_agent" under all the JobAgents ( if more than one ) control directories. Please, assign to Victor. I will take care of the part that sets the version on the SetupProject call

**Comment by vmendez** [comment]
What it is need in dirac.cfg before dirac-configure is the following:
LocalInstallation:
   PythonVersion, Release, LcgVer
LocalSite:
  ReleaseProject,  ReleaseVersion
Currently contextualized for local site dirac-configure:
-o /LocalSite/SubmitPool=Cloud -o /LocalSite/CPUTime=${cpuTime} -o /LocalSite/CloudDriver=${cloudDriver} -o /LocalSite/Site=${siteName}  -o /LocalSite/VMStopPolicy=${vmStopPolicy}  -o /LocalSite/CE=CE-nouse 

It is working without any "pilot version". Which are your purposes with  this dirac.cfg parameters within a VM ?

Additionally, if the ReleaseVersion and ReleaseProject are not corresponding with the one declared at CS, and at the same time the CS is declaring strict release check, then there is no possible communication between VM and DIRAC server.

@fstagni 
@ubeda 
@vmendez
@graciani

**Comment by fstagni** [comment]
I don't know what you mean with "the CS is declaring strict release check". It is anyway needed that the local dirac.cfg is updated with the latest (LHCb)Dirac release version (see mail thread).

**Comment by atsareg** [comment]
Obsoleted since v2
