### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/VMDIRAC#42]
I've written a quick stub with the basic operations needed to install VMDIRAC on my own Wiki. Would be nice to either merge it with DIRACGrid/VMDIRAC or adding them to the diracgrid.org documentation ( so far there is no room for extensions documentation on that portal )

Find them [here](https://github.com/ubeda/VMDIRAC/wiki/VMDIRAC-Installation)

**Comment by vmendez** [comment]
Additionally this is in https://its.cern.ch/jira/browse/LHCBDIRAC-149 and Victor Fernandez also has some installation docu

**Comment by ubeda** [comment]
I do not get the first part of your reply. What do you mean Victor ?

Regarding the second one, would be very nice if Victor Fernandez merges them on the VMDIRAC wiki.

**Comment by ubeda** [comment]
I'd like to mark this issue as closed. What is the status Victor ?

**Comment by vmendez** [comment]
I think this is enough:
https://github.com/DIRACGrid/VMDIRAC/wiki
which references  https://github.com/ubeda/VMDIRAC/wiki/VMDIRAC-Installation
Would you close this #42

**Comment by ubeda** [comment]
Ok.
