### ISSUE TITLE
Stalled VMs

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/VMDIRAC#43]
I have an interesting behavior due to a wrong contextualization.

VMs are up and running. However, the VMonitorAgent does not work as expected ( the userdata was corrupted, do not ask why ). VMDIRAC never set them as running, they are Stalled. This is extremely dangerous because the JobAgent is running but we have absolutely no control over the VM. We need to put in place a mechanism to spot them and wipe them out asap. 

Problem, we may kill the JobAgent while processing a job !

Related with this, I did not find "Stalled" state documented in the DB. It does not look to me as a final state, is it ?

**Comment by vmendez** [comment]
Why is  a contextualization problem affecting only to VM Monitor agent and not to VM Job agent ? 
userdata is passing the scripts which should be able to start VM Monitor as well as VM job agent.
can reproduce the corrupting status ?
I would say in regular basis this VM is not prepared to run
may you clarify these points, please?

Stalled is a final "automatic" status, VM admin should 'stop' the stalled VMs after investigating the source of the problem.

**Comment by ubeda** [comment]
( I started saying do not ask why )

I booted a certain number of IDENTICAL VMs, and some of them run into this odd state where one agent was running where the other was not. However, about 85% of the VMs were running without problems.

I do not know how to reproduce the issue nor where does it come from. 

What about pausing those machines as soon as they enter "stalled status" ? I know in many cases that would be a non-sense, but in very particular cases like this it would be incredibly helpful. What do you think ?

**Comment by vmendez** [comment]
uhm... I see...
I am not sure, I would say in general terms stalled VMs should be deal manually to clarify the problem, onces the problem is "clear" but without a posible solution it has not too much sense to manually stop without further possible debugging...
frankly I have to think about this, any suggestion ?

**Comment by vmendez** [comment]
One more question, please: Are you using vmPolicy static or dynamic? in case of static how many VMs are submitted in a time ?

**Comment by ubeda** [comment]
Is static and 10 VMs were submitted. 
Nevertheless, we cannot assume the cloud infrastructure will always work properly, and this case must be taken into account.

**Comment by vmendez** [comment]
Currently, the VMs "Submitted" would go to "Stalled" at the corresponding time gap at VMDIRAC server.
Then VM operator can click on "Stop" VMs, that is deleting VMs in the Cloud and go to "Halted" status.
I think this is enough by the moment, if so, then close #43

**Comment by ubeda** [comment]
That is fine if you have 10 VMs and you check them every 10 minutes. 

If you have 1000 VMs, you cannot check them by hand every 10 minutes. So, to prevent major damages in the use-case I presented, I think it is quite reasonable to try to pause the instances ( if it does not work it would mean that the VM was actually dead or similar, so no worries.. ) until an operator checks by hand and decides what to do with them.
