### ISSUE TITLE
http references in Web components

### ISSUE THREAD

**Issue by graciani** [DIRACGrid/VMDIRAC#54]
Modern browsers will refuse to access unsecure http resources within an otherwise secure session. 

https://github.com/DIRACGrid/VMDIRAC/blob/b14ed239b7c90cefc029002297c210f222dfd00b/Web/templates/systems/virtualmachines/overview.mako#L6

https://github.com/DIRACGrid/VMDIRAC/blob/b14ed239b7c90cefc029002297c210f222dfd00b/Web/public/javascripts/systems/virtualmachines/vmInstanceInfoWindow.js#L141

**Comment by vmendez** [comment]
v0r8p4

**Comment by vmendez** [comment]
please, close
